### ISSUE TITLE
needs to add a qemu monitor only

### ISSUE THREAD

**Issue by dragon1x** [sylirre/vmConsole#27]
### Problem description

great app 😍

needs to add a qemu monitor only

### Steps to reproduce the behavior.

Thanks

### System information

* Application version:1.5.1
* Android OS version:10
* Device model:rmx2020

**Comment by sylirre** [comment]
Intended behavior as for lots of other QEMU features. This app is not a generic QEMU tool and will not provide access to QEMU internals.

https://github.com/sylirre/vmConsole/wiki/FAQ#how-to-access-qemu-monitor

Don't abuse bug reports to request features. I intentionally do not provide way for this.
